# -*- coding: utf-8 -*-

lista_Provincias = ['Seleccione una provincia...',
            'Araba/Alava',
            'Albacete',
            'Alacant/Alicante',
            'Almeria',
            'Asturias',
            'Avila',
            'Badajoz',
            'Barcelona',
            'Bizkaia',
            'Burgos',
            'Caceres',
            'Cadiz',
            'Cantabria',
            'Castello/Castellon',
            'Ceuta',
            'Ciudad Real',
            'Cordoba',
            'A Coruña',
            'Cuenca',
            'Girona',
            'Granada',
            'Guadalajara',
            'Gipuzkoa',
            'Huelva',
            'Huesca',
            'Illes Balears',
            'Jaen',
            'La Rioja',
            'Las Palmas',
            'Leon',
            'Lleida',
            'Lugo',
            'Madrid',
            'Malaga',
            'Melilla',
            'Murcia',
            'Navarra',
            'Ourense',
            'Palencia',
            'Pontevedra',
            'Salamanca',
            'Santa Cruz de Tenerife',
            'Segovia',
            'Sevilla',
            'Soria',
            'Tarragona',
            'Teruel',
            'Toledo',
            'Valencia/Valencia',
            'Valladolid',
            'Zamora',
            'Zaragoza',
            ]

LISTA_PROVINCIAS = ['Seleccione una provincia...',
            'ARABA/ALAVA',
            'ALBACETE',
            'ALICANTE',
            'ALMERIA',
            'ASTURIAS',
            'AVILA',
            'BADAJOZ',
            'BARCELONA',
            'BIZKAIA',
            'BURGOS',
            'CACERES',
            'CADIZ',
            'CANTABRIA',
            'CASTELLON',
            'CEUTA',
            'CIUDAD REAL',
            'CORDOBA',
            'A CORUÑA',
            'CUENCA',
            'GIRONA',
            'GRANADA',
            'GUADALAJARA',
            'GIPUZKOA',
            'HUELVA',
            'HUESCA',
            'ILLES BALEARS',
            'JAEN',
            'LA RIOJA',
            'LAS PALMAS',
            'LEON',
            'LLEIDA',
            'LUGO',
            'MADRID',
            'MALAGA',
            'MELILLA',
            'MURCIA',
            'NAVARRA',
            'OURENSE',
            'PALENCIA',
            'PONTEVEDRA',
            'SALAMANCA',
            'SANTA CRUZ DE TENERIFE',
            'SEGOVIA',
            'SEVILLA',
            'SORIA',
            'TARRAGONA',
            'TERUEL',
            'TOLEDO',
            'VALENCIA',
            'VALLADOLID',
            'ZAMORA',
            'ZARAGOZA',
            ]
